-- Migration 018: SUPERSEDED
-- Originally intended to add 4 Kia Picanto 2021 (KYV199/KZO779/KYV219/KOS929) as fleet vehicles
-- and reload their fuel logs from the detailed_consumption Excel.
--
-- Superseded because:
-- 1. Those 4 vehicles are historical reference data for comparison with the current electric fleet —
--    they should NOT appear as active or FUERA_DE_SERVICIO vehicles in the fleet management system.
-- 2. All fuel_logs and maintenance_records from migrations 016/017 were cleared and will be
--    reloaded manually via the app's bulk-load feature.
-- 3. The Kia Picanto comparison feature will use a separate data structure (TBD when built).
--
-- This file intentionally contains no executable SQL.
