-- ============================================================
-- Migración 097: listas de chequeo del mantenimiento biomédico, configurables por tipo de equipo
--
-- SISRES: Inventario → Configurar → Listas de chequeo (mostrarChecklistMantenimiento.php, tabla
-- mantenimiento_checklist, sql/checklist_mantenimiento_2026-07-31.sql). Cada tipo de equipo tiene su lista de ítems;
-- el formulario de mantenimiento la muestra según el nombre del equipo y guarda en biomedical_maintenance.chk_items
-- {"ítem": 1 cumple | 0 no cumple}, chk_total y chk_marcados (columnas que ya existen desde la 040).
--
-- `equipo` es la clave normalizada del nombre (mayúsculas, sin tildes, espacios → _), igual que normalizarEquipo() de
-- SISRES (src/lib/biomedico-checklist.ts). La fila GENERAL es la lista para equipos sin una propia.
--
-- Semilla: las 47 listas vigentes de SISRES. ON CONFLICT DO NOTHING: re-ejecutar no pisa lo que se haya
-- editado después desde la aplicación.
--
-- Quién puede qué: leer, los roles que ven Equipos biomédicos; crear/editar/eliminar, ADMIN y MANTENIMIENTO
-- (en SISRES, el cargo Coordinador; el Analista solo las ve). Idempotente.
-- ============================================================

CREATE TABLE IF NOT EXISTS biomedical_checklists (
  equipo     VARCHAR(150) PRIMARY KEY CHECK (equipo ~ '^[A-Z0-9_]+$'),
  items      JSONB NOT NULL CHECK (jsonb_typeof(items) = 'array' AND jsonb_array_length(items) > 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by UUID REFERENCES auth.users(id)
);

INSERT INTO biomedical_checklists (equipo, items) VALUES
  ('AIRE_ACONDICIONADO', '["Verificación inicial","Inspección de la carcasa y rejillas de entrada/salida de aire","Estado del panel de control o control remoto","Verificación del cable de poder o conexión eléctrica","Revisión y limpieza de filtros de aire","Prueba funcional en modo frío y ventilación","Verificación de temperatura de operación","Revisión del drenaje o bandeja de condensado","Limpieza general","Verificación final"]'::jsonb),
  ('ASPIRADOR', '["Verificación inicial","Inspección de manómetro","Revisión del sistema eléctrico","Limpieza y lubricación de viela y recámara de compresión","Limpieza de rotor","Inspección de válvula de alivio y del filtro","Revisión de accesorios","Prueba de funcionamiento","Limpieza general","Verificación final"]'::jsonb),
  ('BASCULA', '["Verificación inicial","Inspección de la carcasa y plataforma.","Estado del visor o pantalla","Revisión del estado de las baterías (SI APLICA)","Verificación de nivelación.","Estado de botones o controles.","Prueba funcional con peso conocido.","Verificación de estabilidad al cargar/pesar","Limpieza general","Verificación final"]'::jsonb),
  ('BASCULA_TALLIMETRO', '["Verificación inicial","Inspección de la plataforma","Estado del visor y de bascula de pesaje","Estado de las vigas de fracciones y kilos","Inspección del tallímetro","Verificación de graduaciones/lecturas de altura","Prueba funcional con peso conocido","Verificación de estabilidad al cargar/pesar","Limpieza general","Verificación final"]'::jsonb),
  ('BOMBA_INFUSION', '["Verificación inicial del encendido y autotest","Estado de la pantalla o visor","Revisión del sistema Eléctrico","Revisión del sistema de arrastre de la línea o peristáltico","Estado del cable de poder y batería","Prueba funcional con agua","Revisión de botones o controles","Prueba de alarmas sonoras y visuales","Verificación del sistema de cierre del set","Limpieza interna y externa"]'::jsonb),
  ('CAMARA', '["Verificación inicial","Inspección de la carcasa y lente","Estado de la imagen (calidad, enfoque, ángulo de visión)","Verificación del cableado y conectores","Revisión del sistema de fijación o soporte","Verificación de la fuente de alimentación","Prueba de grabación o transmisión de video","Revisión de visión nocturna (SI APLICA)","Limpieza general","Verificación final"]'::jsonb),
  ('CAMILLA', '["Verificación inicial","Estado de manijas o soportes laterales","Estado de colchoneta (roturas, limpieza, integridad)","Funcionamiento de barandas (subida, bajada, bloqueo)","Revisión de ruedas (giro libre, bloqueo/frenos)","Ajustes de altura o respaldar","Lubricación de bisagras o puntos móviles","Revisión de cinturones (SI APLICA)","Limpieza general","Verificación final"]'::jsonb),
  ('CELULAR', '["Verificación inicial","Inspección de la carcasa y pantalla","Estado de botones físicos (volumen, encendido)","Verificación del cargador y puerto de carga","Revisión de la batería (carga y autonomía)","Prueba de conectividad (llamadas, WiFi, datos)","Revisión de cámara y micrófono (SI APLICA)","Revisión de aplicaciones y funcionamiento general","Limpieza general","Verificación final"]'::jsonb),
  ('CINTA_METRICA', '["Verificación inicial","Inspección de la cinta","Revisión de funcionamiento","Integridad del sistema retráctil","Estado del gancho, punta o tope inicial","Revisión del estuche o carcasa protectora","Revisión de las marcas de medición (claridad y legibilidad)","Limpieza general","Verificación final"]'::jsonb),
  ('COMPUTADOR', '["Verificación inicial","Inspección de la carcasa y puertos externos","Estado del teclado y mouse","Verificación del cable de poder y conexiones","Revisión del sistema de ventilación y limpieza de polvo","Revisión de funcionamiento del sistema operativo","Verificación de periféricos conectados","Prueba funcional básica","Limpieza general","Verificación final"]'::jsonb),
  ('COMPUTADOR_PORTATIL', '["Verificación inicial","Inspección de la carcasa y bisagras","Estado de la pantalla (brillo, sin manchas ni píxeles muertos)","Revisión del teclado y touchpad","Verificación del cable y adaptador de carga","Revisión de la batería (carga y autonomía)","Revisión del sistema de ventilación y salida de aire","Revisión de puertos y conectores","Prueba funcional del sistema operativo","Limpieza general","Verificación final"]'::jsonb),
  ('DEA', '["Verificación inicial (encendido y autotest automático)","Inspección de la carcasa y tapas","Estado de la pantalla o luces indicadoras","Revisión de electrodos/parches","Estado de conectores y cableado de electrodos","Verificación del nivel de batería o indicador de carga","Revisión de accesorios (kit RCP, tijeras, mascarilla)","Prueba de alarmas sonoras y visuales","Limpieza general","Verificación final"]'::jsonb),
  ('DESFIBRILADOR', '["Verificación inicial","Inspección de la carcasa y pantalla","Revisión de perillas, botones y controles","Estado de los electrodos/paletas (limpieza, integridad)","Verificación del cableado y conectores (sin falsos contactos ni desgaste)","Revisión de la batería (carga, autonomía o indicador de estado)","Prueba funcional con carga y descarga simulada (en tester o simulador)","Prueba de alarmas sonoras y visuales (alertas activas y audibles)","Limpieza general","Verificación final"]'::jsonb),
  ('DINAMOMETRO', '["Verificación inicial","Inspección de carcasa","Estado de la pantalla o visor (encendido, legibilidad)","Revisión de botones o gatillo de medición","Verificación de cableado o batería (carga suficiente o conexiones)","Prueba funcional básica (lectura estable, retorno a cero)","Verificación de sensores","Limpieza general","Verificación final"]'::jsonb),
  ('DVR', '["Verificación inicial","Inspección de la carcasa y panel frontal","Estado de la pantalla o indicadores LED","Verificación del cable de poder y conexiones","Revisión de puertos de entrada de cámaras","Verificación del almacenamiento (disco duro, espacio disponible)","Prueba de grabación y reproducción de video","Verificación de conectividad de red (acceso remoto)","Limpieza general","Verificación final"]'::jsonb),
  ('ECOTONE', '["Verificación inicial","Inspección de la carcasa (fisuras, golpes, integridad general)","Estado de la pantalla o visor (SI APLICA)","Revisión de botones o controles","Verificación del cable de poder o baterías","Estado del transductor (fisuras, cableado, conector)","Prueba funcional de captación de latidos","Verificación de alarmas sonoras y visuales","Limpieza general","Verificación final"]'::jsonb),
  ('ELECTROCARDIOGRAFO', '["Verificación inicial","Inspección de la carcasa y pantalla","Estado del teclado, botones o pantalla táctil","Revisión del cable de poder y enchufe (integridad, conexión segura)","Verificación de batería (carga, autonomía)","Estado de cables y conectores de derivaciones (pinzas y chupas)","Inspección y limpieza de electrodos o accesorios","Prueba funcional de trazado (calidad de señal, sin interferencias)","Limpieza general","Verificación final"]'::jsonb),
  ('EQUIPO_DE_ORGANOS', '["Verificación inicial","Estado del cabezal (lente o especulo, limpieza, sin rayones)","Verificación de la fuente de luz o bombillo","Estado del mango o batería recargable","Revisión de la rosca o sistema de fijación del cabezal","Verificación de lentes o aumentos (claridad, sin suciedad)","Verificación de la batería o conexión eléctrica","Revisión de accesorios adicionales","Limpieza general","Verificación final"]'::jsonb),
  ('FLUJOMETRO', '["Verificación inicial","Inspección visual del tubo medidor (fisuras, rayaduras, limpieza)","Legibilidad de la escala de flujo (números claros, sin desgaste)","Estado del flotador o bola indicadora","Funcionamiento de la perilla de ajuste","Revisión del conector entrada (roscas buen estado, sin fugas)","Estado del adaptador o salida de conexión al paciente","Prueba de estanqueidad","Limpieza general","Verificación final"]'::jsonb),
  ('FONENDOSCOPIO', '["Verificación inicial","Inspección de la cabeza (campana, membrana o diafragma, vastago o conector)","Estado del muelle o arco en Y","Revisión del tubo de conducción","Verificación de las olivas o puntas auriculares","Prueba auditiva básica (sonido claro, sin obstrucciones)","Revisión de piezas intercambiables o accesorios","Limpieza general","Verificación final"]'::jsonb),
  ('GLUCOMETRO', '["Verificación inicial","Inspección de la carcasa","Estado de la pantalla","Revisión de botones de control","Verificación de batería","Revisión del puerto de tiras reactivas","Prueba funcional con solución control o muestra de prueba","Revisión de fechas de vencimiento de tiras reactivas","Limpieza general","Verificación final"]'::jsonb),
  ('GRAMERA', '["Verificación inicial","Inspección de la carcasa","Estado de la plataforma de pesaje","Revisión de la pantalla o visor","Verificación de botones o controles","Prueba con peso ya conocido","Inspección de patas niveladoras o base","Verificación de accesorios adicionales","Limpieza general","Verificación final"]'::jsonb),
  ('IMPRESORA', '["Verificación inicial","Inspección de la carcasa y bandejas de papel","Estado de la pantalla o panel de control","Verificación del cable de poder y conexiones","Revisión del nivel de tinta o tóner","Revisión de cabezales o rodillos de arrastre","Verificación de conectividad (USB / Red / WiFi)","Prueba de impresión de página de prueba","Limpieza general","Verificación final"]'::jsonb),
  ('LAMPARA_CUELLO_DE_CISNE', '["Verificación inicial","Inspección del cabezal o cúpula","Estado del brazo flexible","Revisión de articulaciones o uniones","Verificación de la fuente de luz o bombillo","Estado del cable de poder y enchufe","Revisión del interruptor o regulador de luz","Limpieza del cabezal y reflector/lente","Limpieza general","Verificación final"]'::jsonb),
  ('LAMPARA_PARA_EXAMEN', '["Verificación inicial","Inspección de la carcasa (grietas, deformaciones o piezas sueltas)","Verificar funcionamiento de bombillos o LED","Comprobar intensidad lumínica adecuada","Comprobar funcionamiento de interruptores o zona de contacto eléctrico","Verificación de la batería o conexión eléctrica","Limpieza del reflector o lente","Limpieza general","Verificación final"]'::jsonb),
  ('LARINGOSCOPIO', '["Verificación inicial","Inspección de las valvas","Estado del mango","Verificación del sistema de fijación valva-mango","Estado del bombillo o fuente de luz","Revisión de la batería o sistema de carga","Inspección de contactos eléctricos","Desinfección de las valvas con desinfectante compatible","Limpieza general","Verificación final"]'::jsonb),
  ('MANOMETRO', '["Verificación inicial","Inspección de la carcasa o cubierta","Estado del visor o cristal","Legibilidad de la escala","Verificación de la aguja indicadora","Revisión de roscas y conexiones","Prueba de estanqueidad","Limpieza general","Verificación final"]'::jsonb),
  ('MARTILLO', '["Verificación inicial","Inspección de la cabeza de goma (elasticidad)","Estado del mango o empuñadura","Revisión de superficies metálicas","Comprobación de bordes (sin rebabas ni partes filosas)","Verificación de accesorios adicionales","Limpieza de la cabeza de goma con desinfectante compatible","Limpieza general","Verificación final"]'::jsonb),
  ('MONITOR_DE_SIGNOS_VITALES', '["Verificación inicial","Verificación de encendido y autotest del equipo","Inspección de la carcasa, pantalla y botones","Verificación del cable de poder y enchufe","Revisión de la batería interna","Estado de cables y sensores (ECG, SpO₂, NIBP, temperatura)","Prueba funcional de medición","Verificación de alarmas sonoras y visuales","Limpieza general","Verificación final"]'::jsonb),
  ('MONITOR_PC', '["Verificación inicial","Inspección de la carcasa y pantalla","Estado de botones de control (menú, brillo, contraste)","Verificación del cable de poder y cables de video","Prueba de imagen (brillo, contraste, sin píxeles muertos)","Revisión de puertos de entrada (HDMI, VGA, DisplayPort)","Ajuste de soporte o base (altura, inclinación)","Limpieza de pantalla y carcasa","Limpieza general","Verificación final"]'::jsonb),
  ('NEBULIZADOR', '["Verificación inicial","Inspección de la carcasa","Revisión de accesorios","Revisión del interruptor o controles","Verificación del compresor o generador de ultrasonido","Estado del tubo de aire o manguera","Inspección del frasco nebulizador","Revisión de boquilla","Limpieza general","Verificación final"]'::jsonb),
  ('NEGATOSCOPIO', '["Verificación inicial","Inspección de la carcasa","Estado de la pantalla difusora","Verificación de la iluminación","Revisión de leds","Estado del interruptor o controles","Revisión del sistema Eléctrico","Limpieza general","Verificación final"]'::jsonb),
  ('OFTALMOSCOPIO', '["Verificación inicial","Estado del cabezal (lente o especulo, limpieza, sin rayones)","Verificación de la fuente de luz o bombillo","Estado del mango o batería recargable","Revisión de la rosca o sistema de fijación del cabezal","Verificación de lentes o aumentos (claridad, sin suciedad)","Verificación de la batería o conexión eléctrica","Revisión de accesorios adicionales","Limpieza general","Verificación final"]'::jsonb),
  ('OTOSCOPIO', '["Verificación inicial","Estado del cabezal","Verificación de la fuente de luz o bombillo","Estado del mango o batería recargable","Revisión de la rosca o sistema de fijación del cabezal","Verificación de lentes o aumentos (claridad, sin suciedad)","Verificación de la batería o conexión eléctrica","Revisión de accesorios adicionales","Limpieza general","Verificación final"]'::jsonb),
  ('PULSOXIMETRO', '["Verificación inicial","Inspección de la carcasa","Estado de la pantalla o visor","Revisión de botones, pantalla o controles","Verificación del sensor","Estado del clip o sonda (mecanismo de apertura/cierre)","Prueba funcional en usuario o simulador","Verificación de alarmas sonoras y visuales","Limpieza general","Verificación final"]'::jsonb),
  ('REGULADOR_OXIGENO', '["Verificación inicial","Inspección visual de la carcasa","Estado del manómetro","Verificación de la perilla de ajuste","Inspección de roscas y conexiones","Prueba de estanqueidad","Estado de la válvula de salida y adaptadores","Revisión de accesorios","Limpieza general","Verificación final"]'::jsonb),
  ('ROUTER', '["Verificación inicial (encendido e indicadores LED)","Inspección de la carcasa y antenas","Verificación del cable de poder y cables de red","Estado de los puertos LAN y WAN","Verificación de conectividad a internet","Prueba de señal WiFi (SI APLICA)","Revisión de acceso al panel de administración","Verificación de temperatura de operación","Limpieza general","Verificación final"]'::jsonb),
  ('SILLA_DE_RUEDAS', '["Verificación inicial","Inspección del chasis o bastidor (fisuras, corrosión, soldaduras)","Estado del asiento y respaldo (tapizado, costuras, limpieza)","Revisión de ruedas traseras y delanteras","Estado de mangos de empuje, reposabrazos y reposapiés","Verificación de frenos","Lubricación de partes móviles","Limpieza general","Verificación final"]'::jsonb),
  ('TELEVISOR', '["Verificación inicial","Inspección de la carcasa y pantalla","Estado del control remoto y botones del panel","Verificación del cable de poder y conexiones","Revisión de puertos de entrada (HDMI, USB, AV)","Prueba de imagen (brillo, contraste, color)","Prueba de sonido","Verificación de conectividad WiFi / LAN (SI APLICA)","Revisión del sistema de fijación o soporte","Limpieza general","Verificación final"]'::jsonb),
  ('TENSIOMETRO', '["Verificación inicial","Inspección del brazalete","Estado de válvula de liberación","Revisión del manómetro o display digital","Verificación del tubo de conexión","Revisión del sistema neumático","Verificación de accesorios adicionales","Prueba de estanqueidad","Limpieza general","Verificación final"]'::jsonb),
  ('TERMOHIGROMETRO', '["Verificación inicial","Inspección de la carcasa y pantalla","Estado de botones","Revisión de sensores de temperatura y humedad","Revisión de la batería o pilas","Revisión de funcionamiento","Revisión de alarmas sonoras o visuales","Verificación de fijaciones o soporte","Limpieza general","Verificación final"]'::jsonb),
  ('TERMOMETRO', '["Verificación inicial","Inspección de la carcasa","Estado de la pantalla","Revisión de botones o controles","Revisión de sensores de temperatura","Revisión de la batería o pilas","Prueba funcional de medición","Limpieza general","Verificación final"]'::jsonb),
  ('TORNIQUETE', '["Verificación inicial","Inspección de las correas","Estado de válvula de liberación","Revisión del manómetro","Verificación del tubo de conexión","Revisión del sistema neumático","Prueba de estanqueidad","Limpieza general","Verificación final"]'::jsonb),
  ('VENTILADOR_ASPAS', '["Verificación inicial","Inspección de la carcasa y rejillas de protección","Estado de las aspas o paletas (integridad, sin deformaciones)","Revisión del cable de poder y enchufe","Verificación del interruptor o control de velocidades","Prueba funcional en todas las velocidades disponibles","Revisión del mecanismo de oscilación (SI APLICA)","Lubricación del eje o motor (SI APLICA)","Limpieza general","Verificación final"]'::jsonb),
  ('VENTILADOR_MECANICO', '["Verificación inicial","Inspección de la carcasa y pantalla","Estado de los botones, perillas o pantalla","Verificación del cable de poder y batería interna","Revisión de mangueras, circuitos respiratorios y filtros","Estado del sensor de flujo o presión","Prueba funcional en simulador pulmonar o prueba de autochequeo","Verificación de alarmas sonoras y visuales","Limpieza general","Verificación final"]'::jsonb),
  ('WIFI', '["Verificación inicial (indicadores LED de estado)","Inspección de la carcasa y antenas","Verificación del cable de poder o alimentación PoE","Estado del puerto LAN o conexión a red","Prueba de señal y cobertura WiFi","Verificación de conectividad de dispositivos","Revisión de acceso al panel de administración","Verificación de temperatura de operación","Limpieza general","Verificación final"]'::jsonb),
  ('GENERAL', '["Verificación inicial","Inspección de la carcasa y pantalla","Estado de botones o controles","Revisión de la batería o pilas","Revisión de funcionamiento","Limpieza general","Verificación final"]'::jsonb)
ON CONFLICT (equipo) DO NOTHING;

ALTER TABLE biomedical_checklists ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS biomedical_checklists_select ON biomedical_checklists;
CREATE POLICY biomedical_checklists_select ON biomedical_checklists
  FOR SELECT TO authenticated
  USING (get_user_role() IN ('ADMIN','MANTENIMIENTO','COORDINACION','GERENCIAL','ANALISTA','VISTA'));

DROP POLICY IF EXISTS biomedical_checklists_write ON biomedical_checklists;
CREATE POLICY biomedical_checklists_write ON biomedical_checklists
  FOR ALL TO authenticated
  USING (get_user_role() IN ('ADMIN','MANTENIMIENTO'))
  WITH CHECK (get_user_role() IN ('ADMIN','MANTENIMIENTO'));

-- Igual que la 086: si existe la política restrictiva de TECNICO/AEROPUERTO (076), esta tabla también queda cubierta.
DO $$
BEGIN
  IF to_regprocedure('public.aplicar_politica_rol_restringido(text)') IS NOT NULL THEN
    PERFORM public.aplicar_politica_rol_restringido('biomedical_checklists');
  END IF;
END $$;
